// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7JM2c9rKsJq2MtgHpQAyH
// Component: ZpICpcQ-Op8g4W
import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: HFQysdji1yD9Yg/component
import { NavigationBar } from "@plasmicpkgs/plasmic-nav"; // plasmic-import: jGx9tiKJoex/codeComponent

import { useScreenVariants as useScreenVariantsgyi9F2CGadx1Xj } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: GYI9F2cGadx1XJ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_copy_of_coach_website.module.css"; // plasmic-import: n7JM2c9rKsJq2MtgHpQAyH/projectcss
import * as sty from "./PlasmicMenuHeaderDesktop.module.css"; // plasmic-import: ZpICpcQ-Op8g4W/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ygnpRbGipc6tPF/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: Eg0Wi1P4Mcw9OO/icon
import coachlogoBlacksvgI7FqOqJlgt4WDp from "./images/coachlogoBlacksvg.svg"; // plasmic-import: I7FQOqJlgt4wDP/picture
import icons8Menusvg5GRIf6RnUkXbOh from "./images/icons8Menusvg.svg"; // plasmic-import: 5gRIf6rnUKXbOH/picture

export type PlasmicMenuHeaderDesktop__VariantMembers = {
  base2: "base2";
};
export type PlasmicMenuHeaderDesktop__VariantsArgs = {
  base2?: SingleBooleanChoiceArg<"base2">;
};
type VariantPropType = keyof PlasmicMenuHeaderDesktop__VariantsArgs;
export const PlasmicMenuHeaderDesktop__VariantProps =
  new Array<VariantPropType>("base2");

export type PlasmicMenuHeaderDesktop__ArgsType = {};
type ArgPropType = keyof PlasmicMenuHeaderDesktop__ArgsType;
export const PlasmicMenuHeaderDesktop__ArgProps = new Array<ArgPropType>();

export type PlasmicMenuHeaderDesktop__OverridesType = {
  root?: p.Flex<"div">;
  columns?: p.Flex<"div">;
  hamburgerMenu?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultMenuHeaderDesktopProps {
  base2?: SingleBooleanChoiceArg<"base2">;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicMenuHeaderDesktop__RenderFunc(props: {
  variants: PlasmicMenuHeaderDesktop__VariantsArgs;
  args: PlasmicMenuHeaderDesktop__ArgsType;
  overrides: PlasmicMenuHeaderDesktop__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "base2",
        type: "private",
        variableType: "variant",
        initFunc: true ? ($props, $state, $ctx) => $props.base2 : undefined
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, $props, $ctx);

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgyi9F2CGadx1Xj()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__o6Bkk, {
          [sty.freeBoxbase2__o6Bkkr2Msf]: hasVariant($state, "base2", "base2")
        })}
      >
        {(
          hasVariant($state, "base2", "base2")
            ? true
            : hasVariant(globalVariants, "screen", "mobileOnly")
            ? true
            : true
        ) ? (
          <div
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            className={classNames(projectcss.all, sty.columns, {
              [sty.columnsbase2]: hasVariant($state, "base2", "base2")
            })}
          >
            {(
              hasVariant($state, "base2", "base2")
                ? true
                : hasVariant(globalVariants, "screen", "mobileOnly")
                ? true
                : true
            ) ? (
              <div
                className={classNames(projectcss.all, sty.column__o7PCf, {
                  [sty.columnbase2__o7PCfr2Msf]: hasVariant(
                    $state,
                    "base2",
                    "base2"
                  )
                })}
              >
                {(
                  hasVariant($state, "base2", "base2")
                    ? true
                    : hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vvwIr, {
                      [sty.freeBoxbase2__vvwIrr2Msf]: hasVariant(
                        $state,
                        "base2",
                        "base2"
                      )
                    })}
                  >
                    {(hasVariant($state, "base2", "base2") ? true : true) ? (
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__eumOa,
                          {
                            [sty.linkbase2__eumOaR2Msf]: hasVariant(
                              $state,
                              "base2",
                              "base2"
                            )
                          }
                        )}
                        component={Link}
                        href={`/`}
                        platform={"gatsby"}
                      >
                        {(
                          hasVariant($state, "base2", "base2")
                            ? true
                            : hasVariant(globalVariants, "screen", "mobileOnly")
                            ? true
                            : true
                        ) ? (
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__fvqXt, {
                              [sty.imgbase2__fvqXtR2Msf]: hasVariant(
                                $state,
                                "base2",
                                "base2"
                              )
                            })}
                            displayHeight={"39px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"none" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"123px" as const}
                            src={{
                              src: coachlogoBlacksvgI7FqOqJlgt4WDp,
                              fullWidth: 300,
                              fullHeight: 99,
                              aspectRatio: 3.02439
                            }}
                          />
                        ) : null}
                      </p.PlasmicLink>
                    ) : null}
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ssPb3
                        )}
                      >
                        <button
                          className={classNames(
                            projectcss.all,
                            projectcss.button,
                            projectcss.__wab_text,
                            sty.button___06Ni3
                          )}
                        >
                          {"Sign up"}
                        </button>

                        {true ? (
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__jhQnS
                            )}
                            color={"clear" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___2NcbC
                              )}
                            >
                              {"Log in"}
                            </div>
                          </Button>
                        ) : null}
                      </div>
                    ) : null}
                  </p.Stack>
                ) : null}
              </div>
            ) : null}
            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
            ) ? (
              <div
                className={classNames(projectcss.all, sty.column__wanHo, {
                  [sty.columnbase2__wanHoR2Msf]: hasVariant(
                    $state,
                    "base2",
                    "base2"
                  )
                })}
              >
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1Kd7E)}
                  >
                    {true ? (
                      <button
                        className={classNames(
                          projectcss.all,
                          projectcss.button,
                          projectcss.__wab_text,
                          sty.button___9AQvf
                        )}
                      >
                        {"SIGN IN"}
                      </button>
                    ) : null}
                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1XPTi
                        )}
                      >
                        {"or"}
                      </div>
                    ) : null}

                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button__wgele,
                        {
                          [sty.buttonbase2__wgeleR2Msf]: hasVariant(
                            $state,
                            "base2",
                            "base2"
                          )
                        }
                      )}
                    >
                      {"REQUEST ACCESS"}
                    </button>
                  </p.Stack>
                ) : null}
              </div>
            ) : null}
          </div>
        ) : null}
        {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
          <NavigationBar
            brand={
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__igIjn
                )}
                component={Link}
                href={"#" as const}
                platform={"gatsby"}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__kgugZ)}
                  displayHeight={"40px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: coachlogoBlacksvgI7FqOqJlgt4WDp,
                    fullWidth: 300,
                    fullHeight: 99,
                    aspectRatio: 3.02439
                  }}
                />
              </p.PlasmicLink>
            }
            className={classNames("__wab_instance", sty.navigationBar__xdiKn)}
            closeButton={
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__jFnI4)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                src={"https://static1.plasmic.app/close.svg" as const}
              />
            }
            itemsGap={8 as const}
            menuItems={
              <React.Fragment>
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__plcGb
                  )}
                  component={Link}
                  href={"/" as const}
                  platform={"gatsby"}
                >
                  {"Home"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___1BLm4
                  )}
                  component={Link}
                  href={"/" as const}
                  platform={"gatsby"}
                >
                  {"About"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__maSbi
                  )}
                  component={Link}
                  href={"/" as const}
                  platform={"gatsby"}
                >
                  {"Contact"}
                </p.PlasmicLink>
              </React.Fragment>
            }
            openButton={
              <p.PlasmicImg
                data-plasmic-name={"hamburgerMenu"}
                data-plasmic-override={overrides.hamburgerMenu}
                alt={""}
                className={classNames(sty.hamburgerMenu)}
                displayHeight={"25px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"25px" as const}
                src={{
                  src: icons8Menusvg5GRIf6RnUkXbOh,
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />
            }
            responsiveBreakpoint={768 as const}
          />
        ) : null}
        {(hasVariant($state, "base2", "base2") ? true : true) ? (
          <NavigationBar
            brand={
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__ar3Fh
                )}
                component={Link}
                href={"#" as const}
                platform={"gatsby"}
              >
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__pfsTw, {
                      [sty.imgbase2__pfsTwR2Msf]: hasVariant(
                        $state,
                        "base2",
                        "base2"
                      )
                    })}
                    displayHeight={"39px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"123px" as const}
                    src={{
                      src: coachlogoBlacksvgI7FqOqJlgt4WDp,
                      fullWidth: 300,
                      fullHeight: 99,
                      aspectRatio: 3.02439
                    }}
                  />
                ) : null}
              </p.PlasmicLink>
            }
            className={classNames("__wab_instance", sty.navigationBar__wGm21, {
              [sty.navigationBarbase2__wGm21R2Msf]: hasVariant(
                $state,
                "base2",
                "base2"
              )
            })}
            closeButton={
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___0XtfZ)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                src={"https://static1.plasmic.app/close.svg" as const}
              />
            }
            itemsGap={8 as const}
            menuItems={
              <React.Fragment>
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__c1AjA
                  )}
                  component={Link}
                  href={"/" as const}
                  platform={"gatsby"}
                >
                  {"Home"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__oZpeP
                  )}
                  component={Link}
                  href={"/" as const}
                  platform={"gatsby"}
                >
                  {"About"}
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__htwHh
                  )}
                  component={Link}
                  href={"/" as const}
                  platform={"gatsby"}
                >
                  {"Contact"}
                </p.PlasmicLink>

                <button
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    projectcss.__wab_text,
                    sty.button__hgMzu,
                    {
                      [sty.buttonbase2__hgMzur2Msf]: hasVariant(
                        $state,
                        "base2",
                        "base2"
                      )
                    }
                  )}
                >
                  {"REQUEST ACCESS"}
                </button>
              </React.Fragment>
            }
            openButton={
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__is9FT)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                src={"https://static1.plasmic.app/menu.svg" as const}
              />
            }
            responsiveBreakpoint={768 as const}
          />
        ) : null}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "columns", "hamburgerMenu"],
  columns: ["columns"],
  hamburgerMenu: ["hamburgerMenu"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  columns: "div";
  hamburgerMenu: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuHeaderDesktop__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuHeaderDesktop__VariantsArgs;
    args?: PlasmicMenuHeaderDesktop__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMenuHeaderDesktop__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicMenuHeaderDesktop__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMenuHeaderDesktop__ArgProps,
          internalVariantPropNames: PlasmicMenuHeaderDesktop__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicMenuHeaderDesktop__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuHeaderDesktop";
  } else {
    func.displayName = `PlasmicMenuHeaderDesktop.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuHeaderDesktop = Object.assign(
  // Top-level PlasmicMenuHeaderDesktop renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    hamburgerMenu: makeNodeComponent("hamburgerMenu"),

    // Metadata about props expected for PlasmicMenuHeaderDesktop
    internalVariantProps: PlasmicMenuHeaderDesktop__VariantProps,
    internalArgProps: PlasmicMenuHeaderDesktop__ArgProps
  }
);

export default PlasmicMenuHeaderDesktop;
/* prettier-ignore-end */
