// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7JM2c9rKsJq2MtgHpQAyH
// Component: mLK_azlaN8t68r
import * as React from "react";

import { Link, GatsbyLinkProps as LinkProps } from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ReusableHeader from "../../ReusableHeader"; // plasmic-import: aZG1o9ts_1BbAO/component
import Footer from "../../Footer"; // plasmic-import: yHbgPlkcGh0BHH/component

import { useScreenVariants as useScreenVariantsgyi9F2CGadx1Xj } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: GYI9F2cGadx1XJ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_copy_of_coach_website.module.css"; // plasmic-import: n7JM2c9rKsJq2MtgHpQAyH/projectcss
import * as sty from "./PlasmicAboutUs.module.css"; // plasmic-import: mLK_azlaN8t68r/css

import aboutusbannerimgpng2RDFxBjCoFb3T9 from "./images/aboutusbannerimgpng2.png"; // plasmic-import: rD-fxBjCOFb3T9/picture
import group937SvgOzNkuZf699WA2 from "./images/group937Svg.svg"; // plasmic-import: OZNkuZf699w-A2/picture
import frame910JpgHtHzLexrwy3Eck from "./images/frame910Jpg.jpeg"; // plasmic-import: htHzLEXRWY3eck/picture
import frame909JpgNF6XKwmgxeZqZ from "./images/frame909Jpg.jpeg"; // plasmic-import: nF6xKwmgxeZq-Z/picture
import frame908JpgUjX6WhasuoKapS from "./images/frame908Jpg.jpeg"; // plasmic-import: ujX6WHASUOKapS/picture
import buttonCaretWhitesvg2EkMgwDrEmqPnVl from "./images/buttonCaretWhitesvg2.svg"; // plasmic-import: ekMgwDrEmqPnVl/picture

export type PlasmicAboutUs__VariantMembers = {};
export type PlasmicAboutUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutUs__VariantsArgs;
export const PlasmicAboutUs__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutUs__ArgsType = {};
type ArgPropType = keyof PlasmicAboutUs__ArgsType;
export const PlasmicAboutUs__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutUs__OverridesType = {
  root2?: p.Flex<"div">;
  reusableHeader?: p.Flex<typeof ReusableHeader>;
  section1?: p.Flex<"div">;
  copy?: p.Flex<"div">;
  ctaBlog2?: p.Flex<"div">;
  section11?: p.Flex<"div">;
  cta?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultAboutUsProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

export function Head() {
  return (
    <>
      <meta name="twitter:card" content="summary" />
      <title key="title">{PlasmicAboutUs.pageMetadata.title}</title>
      <meta
        key="og:title"
        property="og:title"
        content={PlasmicAboutUs.pageMetadata.title}
      />
      <meta
        key="twitter:title"
        name="twitter:title"
        content={PlasmicAboutUs.pageMetadata.title}
      />
    </>
  );
}

function PlasmicAboutUs__RenderFunc(props: {
  variants: PlasmicAboutUs__VariantsArgs;
  args: PlasmicAboutUs__ArgsType;
  overrides: PlasmicAboutUs__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgyi9F2CGadx1Xj()
  });

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root2"}
          data-plasmic-override={overrides.root2}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root2
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__x0EtK)} />

          <ReusableHeader
            data-plasmic-name={"reusableHeader"}
            data-plasmic-override={overrides.reusableHeader}
            className={classNames("__wab_instance", sty.reusableHeader)}
          />

          <p.Stack
            as={"div"}
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            hasGap={true}
            className={classNames(projectcss.all, sty.section1)}
          >
            <div className={classNames(projectcss.all, sty.columns___2Qh2C)}>
              <div className={classNames(projectcss.all, sty.column__abVim)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___9TPlD)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"copy"}
                    data-plasmic-override={overrides.copy}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.copy)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__vVvCc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jCopw
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          {
                            <h1
                              className={classNames(
                                projectcss.all,
                                projectcss.h1,
                                projectcss.__wab_text,
                                sty.h1__taShh
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {"Our mission is to "}
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "#3E7CB1" }}
                                >
                                  {"revolutionize"}
                                </span>
                                <React.Fragment>
                                  {" the way companies "}
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "#3E7CB1" }}
                                >
                                  {"train their employees."}
                                </span>
                              </React.Fragment>
                            </h1>
                          }
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__kZUon)}>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sfMac)}
                  />
                ) : null}

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zj79W)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"65%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: aboutusbannerimgpng2RDFxBjCoFb3T9,
                    fullWidth: 1064,
                    fullHeight: 904,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </p.Stack>

          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div className={classNames(projectcss.all, sty.freeBox__h8P1)} />
          ) : null}

          <div
            data-plasmic-name={"ctaBlog2"}
            data-plasmic-override={overrides.ctaBlog2}
            className={classNames(projectcss.all, sty.ctaBlog2)}
          >
            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
            ) ? (
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__kdpG1)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("auto" as const)
                    : ("auto" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("231px" as const)
                    : ("263px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: group937SvgOzNkuZf699WA2,
                  fullWidth: 300,
                  fullHeight: 74,
                  aspectRatio: 4.078652
                }}
              />
            ) : null}

            <div className={classNames(projectcss.all, sty.columns__lQlMl)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__jyfu)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___1QOsV
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                    "Our journey started in 2018 when we partnered with top names in the automotive industry -Maserati and Mercedes, to enhance and digitalize their employee training processes. \n\nWe saw firsthand that even big names in the industry struggled to effectively assess their employees' knowledge and the traditional training methods of attending seminars and assessments were inefficient, boring and often resulted in knowledge gaps.\n\nWith this realization, we set out to create a solution that would address these challenges and deliver results that drive success. \n\nThe result was Coach, a platform designed to detect knowledge gaps and continuously improve employee performance.\nOur platform transforms learning from a one-time event into a continuous process, providing real-time insights into employee performance and improving overall organizational efficiency.\n\nAt Konceptiva, we are dedicated to helping companies solve their employee training challenges and deliver exceptional results."
                  ) : (
                    <React.Fragment>
                      <React.Fragment>
                        {"Our journey started in 2018 when we partnered with "}
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"top names in the automotive industry"}
                      </span>
                      <React.Fragment>{" - "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Maserati"}
                      </span>
                      <React.Fragment>{" and "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Mercedes"}
                      </span>
                      <React.Fragment>
                        {
                          ", to enhance and digitalize their employee training processes. \n\nWe saw firsthand that even big names in the industry struggled to effectively assess their employees' knowledge and the traditional training methods of attending seminars and assessments were inefficient, boring and often resulted in knowledge gaps.\n\nWith this realization, we set out to create a solution that would address these challenges and deliver results that drive success. \n\nThe result was "
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Coach"}
                      </span>
                      <React.Fragment>
                        {
                          ", a platform designed to detect knowledge gaps and continuously improve employee performance.\nOur platform transforms learning from a one-time event into a continuous process, providing real-time insights into employee performance and improving overall organizational efficiency.\n\nAt Konceptiva, we are dedicated to helping companies solve their employee training challenges and deliver exceptional results."
                        }
                      </React.Fragment>
                    </React.Fragment>
                  )}
                </h1>
              </p.Stack>
            </div>

            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"section11"}
                data-plasmic-override={overrides.section11}
                hasGap={true}
                className={classNames(projectcss.all, sty.section11)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__ztAs
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Our latest \n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#3E7CB1" }}
                    >
                      {"news and resources"}
                    </span>
                  </React.Fragment>
                </h1>

                <div
                  className={classNames(projectcss.all, sty.freeBox__qg57)}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.columns__uwq)}>
                <div className={classNames(projectcss.all, sty.column__yfmNe)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rs5Xo)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___74VPz)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: frame910JpgHtHzLexrwy3Eck,
                        fullWidth: 323,
                        fullHeight: 203,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__plW9S
                      )}
                    >
                      {"PRESS ARTICLE"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bhLpt
                      )}
                    >
                      {"Konceptiva: startup of the month January ’22!"}
                    </div>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__kPcIa)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rEr7)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__dERjL)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: frame909JpgNF6XKwmgxeZqZ,
                        fullWidth: 323,
                        fullHeight: 203,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jHxZm
                      )}
                    >
                      {"EVENT"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3F9Xu
                      )}
                    >
                      {"Gamification of Corporate\nTraining - #Session1"}
                    </div>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column___9HxMj)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nYaGh)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gfvl7)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: frame908JpgUjX6WhasuoKapS,
                        fullWidth: 323,
                        fullHeight: 203,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yaqL
                      )}
                    >
                      {"BLOG"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xzbBx
                      )}
                    >
                      {"Here are 5 tips for creating\nan effective course"}
                    </div>
                  </p.Stack>
                </div>
              </div>
            ) : null}
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__gUqb4)} />

          <p.Stack
            as={"div"}
            data-plasmic-name={"cta"}
            data-plasmic-override={overrides.cta}
            hasGap={true}
            className={classNames(projectcss.all, sty.cta)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gtq0
              )}
            >
              {"READY TO START?"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jRoe8
              )}
            >
              {
                "Experience the full power of Coach in action, and see why microlearning is your company’s future."
              }
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___6Vq11)}
            >
              <p.Stack
                as={p.PlasmicLink}
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                hasGap={true}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                component={Link}
                href={"https://calendly.com/kalina-t/30min" as const}
                platform={"gatsby"}
                target={"_blank" as const}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sEKd
                  )}
                >
                  {"GET STARTED"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___7Dyc)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"15px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: buttonCaretWhitesvg2EkMgwDrEmqPnVl,
                    fullWidth: 108,
                    fullHeight: 150,
                    aspectRatio: 0.722222
                  }}
                />
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root2: [
    "root2",
    "reusableHeader",
    "section1",
    "copy",
    "ctaBlog2",
    "section11",
    "cta",
    "link",
    "footer"
  ],
  reusableHeader: ["reusableHeader"],
  section1: ["section1", "copy"],
  copy: ["copy"],
  ctaBlog2: ["ctaBlog2", "section11"],
  section11: ["section11"],
  cta: ["cta", "link"],
  link: ["link"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root2: "div";
  reusableHeader: typeof ReusableHeader;
  section1: "div";
  copy: "div";
  ctaBlog2: "div";
  section11: "div";
  cta: "div";
  link: "a";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutUs__VariantsArgs;
    args?: PlasmicAboutUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAboutUs__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAboutUs__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root2") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root2"),
  {
    // Helper components rendering sub-elements
    reusableHeader: makeNodeComponent("reusableHeader"),
    section1: makeNodeComponent("section1"),
    copy: makeNodeComponent("copy"),
    ctaBlog2: makeNodeComponent("ctaBlog2"),
    section11: makeNodeComponent("section11"),
    cta: makeNodeComponent("cta"),
    link: makeNodeComponent("link"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "About Us",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
